# Generated by Django 4.2 on 2026-04-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=100)),
                ("account_type", models.CharField(max_length=50)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("currency", models.CharField(default="TND", max_length=10)),
                ("status", models.CharField(default="active", max_length=50)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "accounts",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="BankParam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("param_key", models.CharField(max_length=100, unique=True)),
                ("param_value", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "bank_params",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=100)),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                ("transaction_type", models.CharField(max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("currency", models.CharField(default="TND", max_length=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("transaction_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "bank_transactions",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=255)),
                ("summary", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(default="confirmed", max_length=50)),
                ("calendar_sync", models.BooleanField(default=False)),
                (
                    "calendar_event_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "bookings",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="Cheque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=100)),
                ("cheque_number", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("payee", models.CharField(blank=True, max_length=255, null=True)),
                ("issue_date", models.DateField()),
                ("status", models.CharField(default="pending", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "cheques",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("cin", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "customers",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="Reclamation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=255)),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("complaint", models.TextField()),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.CharField(default="pending", max_length=50)),
                ("priority", models.CharField(default="normal", max_length=50)),
                (
                    "assigned_to",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("resolution", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "reclamations",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="RecoveryLoan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=255)),
                ("loan_number", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "remaining_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("status", models.CharField(default="active", max_length=50)),
                ("due_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "recovery_loans",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("googleId", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(default="customer", max_length=50)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("cin", models.CharField(blank=True, max_length=50, null=True)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                ("google_access_token", models.TextField(blank=True, null=True)),
                ("picture", models.URLField(blank=True, null=True)),
                (
                    "customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "users",
                "ordering": [],
            },
        ),
    ]
